apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-publisher-workers
  labels:
    app: message-publisher-workers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-publisher-workers
  template:
    metadata:
      labels:
        app: message-publisher-workers
    spec:
      containers:
      - name: workers
        image: message-publisher-workers:latest
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/health-check.sh
          initialDelaySeconds: 30
          periodSeconds: 15
